Updates GitHub Actions (#298)
Co-authored-by: Kyle Aure <KyleJAure@gmail.com>

diff --git a/.github/workflows/microshed-ci.yml b/.github/workflows/microshed-ci.yml
--- a/.github/workflows/microshed-ci.yml
+++ b/.github/workflows/microshed-ci.yml
@@ -1,6 +1,7 @@
 name: MicroShed CI
 
 on:
+  push:
   pull_request:
     branches: 
     - main
@@ -17,26 +18,23 @@ env:
   LANG: en_US.UTF-8
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ ubuntu-latest ]
+        java: [ 11 ]
+      fail-fast: false
+      max-parallel: 4
+    name: Build ${{ matrix.java }}, ${{ matrix.os }}
+
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
     - name: Set up Java
-      uses: joschi/setup-jdk@v2
+      uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
       with:
-        java-version: 11
-        openjdk_impl: openj9
-    - name: Apply repository caches
-      uses: actions/cache@v2
-      with:
-        path: |
-          ~/.gradle/caches/modules-2
-          !~/.gradle/caches/modules-2/org.microshed*
-          ~/.gradle/wrapper
-          ~/.m2/repository/
-          !~/.m2/repository/org/microshed/
-        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/pom.xml') }}
-        restore-keys: |
-          ${{ runner.os }}-gradle-
+        java-version: ${{ matrix.java }}
+        distribution: 'temurin'
+        cache: gradle
     - name: Build with Gradle
       run: |
         chmod +x gradlew
@@ -44,6 +42,7 @@ jobs:
   integration_tests:
     name: Tests - ${{matrix.category}}
     runs-on: ubuntu-latest
+    needs: build
     timeout-minutes: 20
     strategy:
       fail-fast: false
@@ -71,54 +70,32 @@ jobs:
               quarkus-app
               wildfly-app
     steps:
-    - uses: actions/checkout@v2
-    - name: Set up Java
-      uses: joschi/setup-jdk@v2
-      with:
-        java-version: 11
-        openjdk_impl: openj9
-    - uses: testspace-com/setup-testspace@v1
-      with:
-        domain: ${{ github.repository_owner }}
-    - name: Apply repository caches
-      uses: actions/cache@v2
-      with:
-        path: |
-          ~/.gradle/caches/modules-2
-          !~/.gradle/caches/modules-2/org.microshed*
-          ~/.gradle/wrapper
-          ~/.m2/repository/
-          !~/.m2/repository/org/microshed/
-        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/pom.xml') }}
-        restore-keys: |
-          ${{ runner.os }}-gradle-
-    - name: Run integration tests
-      shell: bash
-      env:
-        TEST_PROJECTS: ${{matrix.projects}}
-        CATEGORY: ${{matrix.category}}
-      run: |
-        chmod +x gradlew
-        echo "org.gradle.daemon=false" >> gradle.properties
-        
-        echo "Will be running projects $TEST_PROJECTS"
-        for TEST_PROJECT in $TEST_PROJECTS
-        do
-          if [[ ! -d "sample-apps/$TEST_PROJECT" ]]; then
-            echo "::error::Test project $TEST_PROJECT does not exist.";
-            exit 1;
-          fi
-        done
-        
-        for TEST_PROJECT in $TEST_PROJECTS
-        do
-          echo "### BEGIN running test project $TEST_PROJECT"
-          ./gradlew :microshed-testing-$TEST_PROJECT:test
-          echo "### END running test project $TEST_PROJECT";
-        done
-        
-        echo "Done running all tests."
-    - name: Upload test results
-      if: always()
-      run: |
-        testspace [${{matrix.category}}]sample-apps/*/build/test-results/**/*.xml
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Set up Java
+        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
+        with:
+          java-version: 11
+          distribution: 'temurin'
+          cache: gradle
+      - name: Run integration tests
+        shell: bash
+        env:
+          TEST_PROJECTS: ${{matrix.projects}}
+          CATEGORY: ${{matrix.category}}
+        run: |
+          chmod +x gradlew
+          echo "org.gradle.daemon=false" >> gradle.properties
+  
+          echo "Will be running projects $TEST_PROJECTS"
+          for TEST_PROJECT in $TEST_PROJECTS
+          do
+            if [[ ! -d "sample-apps/$TEST_PROJECT" ]]; then
+              echo "::error::Test project $TEST_PROJECT does not exist.";
+              exit 1;
+            fi
+            echo "### BEGIN running test project $TEST_PROJECT"
+              ./gradlew :microshed-testing-$TEST_PROJECT:test
+              echo "### END running test project $TEST_PROJECT";
+          done
+  
+          echo "Done running all tests."
